name: pytorch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blosc=1.21.3=h6c2663c_0
  - boost-cpp=1.74.0=h5b4e17d_6
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.7.22=h56e8100_0
  - cairo=1.16.0=h63a05c6_1001
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - cfitsio=3.470=h2bbff1b_7
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cryptography=39.0.1=py310h21b164f_0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.5.0=h63175ca_1
  - faiss-gpu=1.7.4=h949689a_0
  - fontconfig=2.14.1=h9c4af85_2
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - freexl=1.0.6=ha8e266a_0
  - geos=3.8.0=h33f27b4_0
  - geotiff=1.7.0=h4545760_1
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.12.1=nompi_h2a0e4a3_100
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - joblib=1.2.0=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - kealib=1.5.0=hde4a422_1
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h6609f42_0
  - lcms2=2.15=ha5c8aab_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang13=14.0.6=default_h8e68704_1
  - libcurl=8.2.1=h86230a5_0
  - libdeflate=1.17=h2bbff1b_0
  - libexpat=2.5.0=h63175ca_1
  - libfaiss=1.7.4=cuda112h33bf9e0_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.4.4=hd77b12b_0
  - libgdal=3.6.2=hd879e17_3
  - libiconv=1.16=h2bbff1b_2
  - libkml=1.3.0=h9859afa_1014
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libnetcdf=4.8.1=h6685c40_4
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=hb652d5d_1
  - libspatialite=4.3.0a=h6ec8781_23
  - libssh2=1.10.0=hcd4344a_2
  - libuv=1.44.2=h2bbff1b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.3=h0ad7f3c_0
  - libxslt=1.1.37=h2bbff1b_0
  - libzip=1.8.0=h49b8836_0
  - lz4-c=1.9.4=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.7.1=py310haa95532_1
  - matplotlib-base=3.7.1=py310h4ed8f06_1
  - mkl=2023.1.0=h8bd8f75_46356
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.6=py310h4ed8f06_1
  - mkl_random=1.2.2=py310h4ed8f06_1
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - numpy=1.26.0=py310hf667824_0
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=1.1.1w=hcfcfb64_0
  - packaging=23.0=py310haa95532_0
  - pcre=8.45=hd77b12b_0
  - pcre2=10.42=h0ff8eda_0
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.1.2=py310haa95532_0
  - pixman=0.38.0=hfa6e2cd_1003
  - ply=3.11=py310haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - poppler=22.12.0=h0bf3bde_2
  - poppler-data=0.4.12=hd8ed1ab_0
  - proj=6.2.1=h3758d61_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.12=h966fe2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.1=py3.10_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - qhull=2020.2=h70d2c02_2
  - qt-main=5.15.2=h6072711_9
  - qt-webengine=5.15.9=hb9a9bb5_5
  - qtwebkit=5.212=h2bbfb41_5
  - scikit-learn=1.2.2=py310hd77b12b_1
  - scipy=1.10.1=py310h309d312_1
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tiledb=2.3.3=h3649cd2_2
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.12.1=py310_cu113
  - torchvision=0.13.1=py310_cu113
  - tornado=6.2=py310h2bbff1b_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.36.32532=hfdfe4a8_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xerces-c=3.2.4=h63175ca_3
  - xz=5.4.2=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - absl-py==1.4.0
      - aermanager==0.3.0
      - aiofiles==23.2.1
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - altair==5.2.0
      - annotated-types==0.6.0
      - ansi2html==1.8.0
      - antlr4-python3-runtime==4.13.1
      - anyio==4.2.0
      - apptools==5.2.1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.2.1
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - autograd==1.6.2
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - bleach==6.1.0
      - cachetools==5.3.3
      - chex==0.1.85
      - click==8.1.6
      - clu==0.0.11
      - colorama==0.4.6
      - comm==0.1.3
      - configargparse==1.7
      - configobj==5.0.8
      - contextlib2==21.6.0
      - dash==2.11.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dataclass-array==1.5.1
      - debugpy==1.6.7
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - distinctipy==1.3.4
      - dm-tree==0.1.8
      - docstring-parser==0.15
      - dotmap==1.3.30
      - dv==1.0.12
      - einops==0.7.0
      - envisage==7.0.3
      - et-xmlfile==1.1.0
      - etils==1.7.0
      - exceptiongroup==1.2.0
      - executing==1.2.0
      - exifread==3.0.0
      - faiss-cpu==1.7.4
      - fast-pytorch-kmeans==0.2.0.1
      - fastapi==0.109.0
      - fastjsonschema==2.18.0
      - ffmpy==0.3.1
      - filelock==3.13.1
      - flask==2.2.5
      - flatbuffers==23.5.26
      - flax==0.8.1
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.12.2
      - future==0.18.3
      - gast==0.5.4
      - gdal==3.4.3
      - google-auth==2.28.1
      - google-auth-oauthlib==1.2.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.62.0
      - googledrivedownloader==0.4
      - gradio==3.41.2
      - gradio-client==0.5.0
      - grpcio==1.62.0
      - h11==0.14.0
      - h5py==3.10.0
      - haversine==2.8.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.2
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.9
      - immutabledict==4.1.0
      - importlib-resources==6.1.1
      - ipykernel==6.25.0
      - ipython==8.14.0
      - ipywidgets==8.0.7
      - isoduration==20.11.0
      - itsdangerous==2.1.2
      - jax==0.4.25
      - jaxlib==0.4.25
      - jedi==0.18.2
      - jinja2==3.1.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.18.4
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.3.0
      - jupyter-console==6.6.3
      - jupyter-core==5.3.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.1
      - jupyter-server==2.12.4
      - jupyter-server-terminals==0.5.1
      - jupyterlab==4.0.10
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.2
      - jupyterlab-widgets==3.0.8
      - keras==2.15.0
      - lark==1.1.9
      - lazy-loader==0.3
      - libclang==16.0.6
      - libtiff==0.4.2
      - lightning-utilities==0.10.1
      - lxml==4.9.3
      - lz4==4.3.3
      - mapbox-earcut==1.0.1
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib-inline==0.1.6
      - mayavi==4.8.1
      - mdurl==0.1.2
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.2.0
      - msgpack==1.0.7
      - multidict==6.0.5
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.14.1
      - nbformat==5.7.0
      - nest-asyncio==1.5.6
      - networkx==3.2.1
      - notebook==7.0.6
      - notebook-shim==0.2.3
      - oauthlib==3.2.2
      - onedrivedownloader==1.1.3
      - open3d==0.17.0
      - opencv-contrib-python==4.8.0.74
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - optax==0.2.0.dev0
      - orbax-checkpoint==0.4.4
      - orjson==3.9.10
      - overrides==7.4.0
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pickleshare==0.7.5
      - platformdirs==3.9.1
      - plotly==5.15.0
      - prettytable==3.10.0
      - prometheus-client==0.19.0
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pyface==8.0.0
      - pygame==2.5.2
      - pygments==2.15.1
      - pykml==0.2.0
      - pymap3d==3.0.1
      - pynvml==11.5.0
      - pyproject-toml==0.0.10
      - pyshp==2.3.1
      - python-json-logger==2.0.7
      - python-multipart==0.0.6
      - pytorch-lightning==2.1.0
      - pytorch-metric-learning==2.4.1
      - pytz==2023.3.post1
      - pywin32==306
      - pywinpty==2.0.12
      - pyyaml==6.0.1
      - pyzmq==25.1.0
      - qtconsole==5.5.1
      - qtpy==2.4.1
      - referencing==0.30.0
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.0
      - rpds-py==0.9.2
      - rsa==4.9
      - safetensors==0.4.2
      - scenic==0.0.1
      - scikit-image==0.22.0
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - setuptools==68.2.2
      - shapely==1.8.5.post1
      - shellingham==1.5.4
      - shtab==1.7.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.2
      - starlette==0.35.1
      - tenacity==8.2.2
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.15.0
      - tensorflow-addons==0.22.0
      - tensorflow-datasets==4.9.4
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorflow-metadata==1.14.0
      - tensorstore==0.1.45
      - termcolor==2.4.0
      - terminado==0.18.0
      - tf==1.0.0
      - tifffile==2023.9.26
      - timm==0.9.16
      - tinycss2==1.2.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - toolz==0.12.0
      - torchcam==0.3.2
      - torchgeometry==0.1.2
      - torchmetrics==1.3.1
      - tqdm==4.65.0
      - traitlets==5.9.0
      - traits==6.4.1
      - traitsui==8.0.0
      - transformations==2022.9.26
      - typeguard==2.13.3
      - typer==0.9.0
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.9.0
      - tyro==0.7.3
      - tzdata==2023.3
      - uri-template==1.3.0
      - uvicorn==0.25.0
      - vtk==9.2.6
      - wcwidth==0.2.6
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - websockets==11.0.3
      - werkzeug==2.2.3
      - widgetsnbextension==4.0.8
      - wrapt==1.14.1
      - yarl==1.9.4
      - zipp==3.17.0
      - zstd==1.5.5.1
prefix: D:\miniconda\envs\pytorch
